# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: get-Traffic-Action

on:
  schedule:
    - cron:  '0 9 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.3.1"
    - name: Install dependencies
      run: |
        poetry install
    - name: show poetry env info
      run: |
        poetry env info
    - name: run Python 
      run: |
        poetry run python main.py
      env:
        MY_TRAFFIC_TOKEN: ${{ secrets.MY_TRAFFIC_TOKEN }}
